apiVersion: v1
kind: PersistentVolume
metadata:
  name: pongs-pv
spec:
  storageClassName: pongs-sc
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0
